<?php

	$zImagenUAalt = "Web de la UA";
	$zImagenEPSalt = "Página Principal EPSA";
	$zEPSImagen ="./imagenes/tituloPrincipal_ESreloj.gif";

	
?>
	<div style="background-color:#ffffff">
	<div class="textoBlanco" style="height:70px">
		<span style="float:left">
			<a href="/"  title="<?php echo $zEPSImagen?>"><img class="left" style="border: 0 none " src="<?php echo $zEPSImagen ?>" alt="<?php echo $zImagenEPSalt?>" title="<?php echo $zImagenEPSalt?>" /></a><br /><br /><br />
		</span>
		<a href="http://www.ua.es" title="<?php echo $zImagenUAalt?>"><img class="right" style="float:right;border:0 none" src="./imagenes/logouap.gif" alt="<?php echo $zImagenUAalt?>" title="<?php echo $zImagenUAalt?>" /></a>
	</div>
	</div>
