<?php


//Definición de constantes globales


//Nombre de la Base de Datos a utilizar
$gBaseDatos = "nombre base de datos";

//IP del servidor de la Base de Datos
$gIP="ip servidor base de datos";

//Login del usuario de la BD
$gUser = "usuario base de datos";

//Password del usuario de la BD
$gPassword = "pass del usuario BD";

$comunidadsnmp="";

//Rama OID de SNMP
$oidPrimeraParte="1.3.6.1.4.1.";
$oidSegundaParte="52.2501.1.12."; //XXX Antes "52.2501.1.12.4.1."


$IdiomaEPS="cas";

$g_docTypeStrict = "<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Strict//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd\">\n";
$g_docType = "<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\n";

?>
