/*
SQLyog - Free MySQL GUI v5.19
Host - 5.1.73-log : Database -  EPSAlicante
*********************************************************************
Server version : 5.1.73-log
*/

SET NAMES utf8;

SET SQL_MODE='';

create database if not exists `controlred`;

USE `controlred`;

SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO';

/*Table structure for table `LABORATORIOS` */

DROP TABLE IF EXISTS `LABORATORIOS`;

CREATE TABLE `LABORATORIOS` (
  `CODLAB` varchar(10) NOT NULL DEFAULT '',
  `NOMBREOLD` varchar(255) NOT NULL DEFAULT '',
  `IP` varchar(15) NOT NULL DEFAULT '',
  `MASCARA` varchar(15) NOT NULL DEFAULT '',
  `GATEWAY` varchar(15) NOT NULL DEFAULT '',
  `BROADCAST` varchar(15) NOT NULL DEFAULT '',
  `FIREWALL` varchar(15) NOT NULL DEFAULT '',
  PRIMARY KEY (`CODLAB`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 PACK_KEYS=1;

/*Table structure for table `LABORATORIOSTR` */

DROP TABLE IF EXISTS `LABORATORIOSTR`;

CREATE TABLE `LABORATORIOSTR` (
  `CODLAB` varchar(10) NOT NULL DEFAULT '',
  `IDIOMA` varchar(5) NOT NULL DEFAULT '',
  `NOMBRE` varchar(255) NOT NULL DEFAULT '',
  `DESCRIP` varchar(255) NOT NULL DEFAULT '',
  `MATERIAL` text NOT NULL,
  PRIMARY KEY (`CODLAB`,`IDIOMA`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;


DROP TABLE IF EXISTS `ROUTERACLITEMS`;


CREATE TABLE `ROUTERACLITEMS` (
  `NOMBRE` varchar(50) NOT NULL DEFAULT '',
  `ITEM` int(11) NOT NULL DEFAULT '0',
  `RESTRICCION` varchar(20) DEFAULT NULL,
  `PROTOCOLO` varchar(20) DEFAULT NULL,
  `IPORIGEN` varchar(20) DEFAULT NULL,
  `MASCARAORIGEN` varchar(20) DEFAULT NULL,
  `IPDESTINO` varchar(20) DEFAULT NULL,
  `MASCARADESTINO` varchar(20) DEFAULT NULL,
  `TOSE` varchar(5) DEFAULT NULL,
  `OPERPUERTOORIGEN` varchar(5) DEFAULT NULL,
  `PUERTOORIGEN` double DEFAULT NULL,
  `OPERPUERTODESTINO` varchar(5) DEFAULT NULL,
  `PUERTODESTINO` double DEFAULT NULL,
  `ESTADO` int(11) DEFAULT NULL,
  `DESCRIPCION` varchar(50) DEFAULT NULL,
  `SIEMPREACTIVO` varchar(50) DEFAULT NULL,
  `OPCIONACTIVA` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`NOMBRE`,`ITEM`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS `HISTORICOGENERAL`;

CREATE TABLE `HISTORICOGENERAL` (
  `CODHIS` int(5) unsigned zerofill NOT NULL AUTO_INCREMENT,
  `RUSER` varchar(20) NOT NULL DEFAULT '',
  `RADDR` varchar(255) NOT NULL DEFAULT '',
  `FECHA` date NOT NULL DEFAULT '0000-00-00',
  `HORA` time NOT NULL DEFAULT '00:00:00',
  `OPERACION` char(1) NOT NULL DEFAULT '',
  `DESCRIP` text,
  `APLICACION` varchar(50) NOT NULL DEFAULT '',
  `IDIOMA` char(3) DEFAULT 'cas',
  PRIMARY KEY (`CODHIS`),
  KEY `FECHA` (`FECHA`)
) ENGINE=InnoDB AUTO_INCREMENT=11453976 DEFAULT CHARSET=latin1 PACK_KEYS=1;

DROP TABLE IF EXISTS `GRUPOSWEB`; 

CREATE TABLE `GRUPOSWEB` (
  `CODGRU` varchar(20) NOT NULL DEFAULT '',
  `DESCRIP` varchar(255) NOT NULL DEFAULT '',
  `GIDNUMBER` int(5) unsigned zerofill NOT NULL AUTO_INCREMENT,
  `BORRABLE` char(1) NOT NULL DEFAULT 'N',
  `VALIDEZPWD` int(5) NOT NULL DEFAULT '30',
  `CORREO` varchar(255) NOT NULL DEFAULT '',
  PRIMARY KEY (`CODGRU`),
  UNIQUE KEY `GIDNUMBER` (`GIDNUMBER`)
) ENGINE=InnoDB AUTO_INCREMENT=822 DEFAULT CHARSET=latin1 PACK_KEYS=1;

DROP TABLE IF EXISTS `USUARIOSWEB`;
CREATE TABLE `USUARIOSWEB` (
  `CODUSU` varchar(20) NOT NULL DEFAULT '',
  `PREGUNTA` varchar(255) NOT NULL DEFAULT '',
  `RESPUESTA` varchar(255) NOT NULL DEFAULT '',
  `CORREO` varchar(255) NOT NULL DEFAULT '',
  `PASSWORD` varchar(50) NOT NULL DEFAULT '',
  `CN` varchar(50) DEFAULT NULL,
  `SN` varchar(50) DEFAULT NULL,
  `UIDNUMBER` int(5) unsigned zerofill NOT NULL AUTO_INCREMENT,
  `HOMEDIRECTORY` varchar(30) NOT NULL DEFAULT '',
  `LOGINSHELL` varchar(20) NOT NULL DEFAULT '',
  `GIDNUMBER` int(5) unsigned zerofill NOT NULL DEFAULT '00000',
  `BORRABLE` char(1) NOT NULL DEFAULT 'S',
  `VALIDEZPWD` int(5) NOT NULL DEFAULT '0',
  PRIMARY KEY (`CODUSU`),
  UNIQUE KEY `UIDNUMBER` (`UIDNUMBER`),
  KEY `GIDNUMBER` (`GIDNUMBER`)
) ENGINE=InnoDB AUTO_INCREMENT=123261 DEFAULT CHARSET=latin1 PACK_KEYS=1;
/*Data for the table `LABORATORIOS` */

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
